name: hello world
on : workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "welcome to my github profile howare you team"
          echo "this is my 2nd line of the code which i'm writing now let's see the result"
          echo "third line is this"
          
  
