name: hello world
on : workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step of the code
        run: echo "building code artificats"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: testing code
        run: echo "testing code...!!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps :
      - name: deploying the application
        run: echo "deploying application after test-passed"
        
          
  
